/**
 * Programme Collection Data
 *
 * This file contains the programme data extracted from the provided row data.
 * Each programme entry includes comprehensive information about Community Jameel programmes,
 * labs, scholarships, and initiatives.
 */

export const programmeData = [
  {
    id: '270e420a-c5b1-4037-9516-6b43037deeac',
    slug: 'jameel-house-of-traditional-arts-in-jeddah',
    name: 'Jameel House of Traditional Arts in Jeddah',
    nameArabic: '',
    shortname: 'Jameel House in Jeddah',
    shortNameArabic: '',
    type: 'Programme',
    byline:
      'Preserving Saudi heritage through traditional arts education and training',
    bylineArabic: '',
    text: '',
    summaryLongEnglish: '',
    summaryLongArabic: '',
    fieldEnglishResearch: '',
    fieldArabicResearch: '',
    headquartersEnglish: '',
    headquartersArabic: '',
    yearEstablished: null,
    yearClosed: '',
    order: '',
    status: 'published',
    createdOn: '8 April 2025',
    website: '',
    linkToPage: '',
    buttonText: '',
    twitter: '',
    facebook: '',
    instagram: '',
    linkedin: '',
    youtube: '',
    mainVideo: '',
    card: {
      url: '',
      alt: ''
    },
    hero: {
      url: '',
      alt: ''
    },
    openGraph: {
      url: '',
      alt: ''
    },
    logoSvgDark: {
      url: '',
      alt: ''
    },
    logoSvgOriginalRatio: {
      url: '',
      alt: ''
    },
    logoSvgSquareOverlay: {
      url: '',
      alt: ''
    },
    logoSvgLightOriginalRatio: {
      url: '',
      alt: ''
    },
    partners: [
      {
        name: "The King's Foundation",
        slug: 'the-kings-foundation',
        arabicName: ''
      },
      {
        name: 'Community Jameel',
        slug: 'community-jameel',
        arabicName: 'مجتمع جميل'
      }
    ],
    leadership: [],
    relatedProgrammes: [],
    features: [],
    impact01: '',
    impact01Title: '',
    impact01TitleArabic: '',
    impact02: '',
    impact02Title: '',
    impact02TitleArabic: '',
    impact03: '',
    impact03Title: '',
    impact03TitleArabic: '',
    impact04: '',
    impact04Title: '',
    impact04TitleArabic: '',
    impact05: '',
    impact05Title: '',
    impact05TitleArabic: '',
    impact06: '',
    impact06Title: '',
    impact06TitleArabic: '',
    latitude: '',
    longitude: '',
    colour: '',
    pushToGr: '',
    newsOnOff: false,
    tags: [],
    metaDescription: '',
    metaDescriptionArabic: ''
  },
  {
    id: 'c5691e49-869c-4202-906a-0bd673e38265',
    slug: 'jameel-house-of-world-traditional-arts-in-scotland',
    name: 'Jameel House of World Traditional Arts in Scotland ',
    nameArabic: 'بيت جميل للفنون التراثية العالمية في اسكتلندا',
    shortname: 'Jameel House in Scotland',
    shortNameArabic: 'بيت جميل في اسكتلندا',
    type: 'Programme',
    byline:
      'A centre for the study of traditional arts from around the world at Dumfries House',
    bylineArabic: '',
    text: '<p id="">The Jameel House of World Traditional Arts in Scotland is a school for the study of the traditional arts from around the world. It is located on the Dumfries House estate and is a collaboration between The King\'s Foundation and Community Jameel.</p>',
    summaryLongEnglish:
      '<p id="">Set in the grounds of Dumfries House in East Ayrshire, the Jameel House of World Traditional Arts in Scotland is a school offering workshops, short courses and residencies in the traditional arts from around the world, including sacred geometry, woodwork and gypsum carving.</p><p id="">With a programme developed and delivered by The King\'s Foundation School of Traditional Arts, the Jameel House in Scotland is part of a network of Jameel Houses established by Community Jameel and The King\'s Foundation, alongside those in Cairo and Jeddah.</p><p id=""><strong id="">About Dumfries House</strong></p><p id="">Dumfries House, part of The King\'s Foundation, is an 18th-century house and 2,000-acre estate. </p><p id="">Saved in 2007 by the intervention of His Royal Highness The Prince Charles, Duke of Rothesay (later His Majesty King Charles III), Dumfries House combines the neoclassical architecture of Robert Adam with the furniture of Thomas Chippendale and leading 18th-century Scottish cabinet makers.</p>',
    summaryLongArabic:
      '<p id="">يقع بيت جميل للفنون التراثية العالمية في اسكتلندا ضمن أراضي دمفريز هاوس في إيست آيرشاير، ويُقدم مجموعة من ورش العمل والدورات القصيرة والإقامات الفنية التي تغطي طيفاً واسعاً من الفنون التراثية المستوحاة من ثقافات متعددة حول العالم. ومن بين التخصصات التي يتيحها المركز الهندسة المقدسة، والأعمال الخشبية، والنحت على الجبس </p><p id=""> تم تطوير وتنفيذ برنامج بيت جميل للفنون التراثية العالمية في اسكتلندا من قِبَل مدرسة مؤسسة الملك للفنون التقليدية، ويشكل جزءاً من شبكة بيوت جميل التي أطلقها مجتمع جميل بالتعاون مع مؤسسة الملك، إلى جانب الفروع الأخرى في القاهرة وجدة</p><p id=""><strong id="">نبذة عن دمفريز هاوس</strong></p><p id="">يُعد دمفريز هاوس، التابع لمؤسسة الملك، معلماً تاريخياً فريداً من نوعه، إذ يعود تاريخه إلى القرن الثامن عشر، ويمتد على مساحة 2000 فدان، مما يجعله واحداً من أبرز القصور التاريخية في المملكة المتحدة</p><p id="">وقد جرى إنقاذ هذا القصر في عام 2007 بفضل تدخل صاحب السمو الملكي الأمير تشارلز، دوق روثيساي آنذاك (جلالة الملك تشارلز الثالث لاحقاً)، ليظل شاهداً على روعة العمارة الكلاسيكية الجديدة التي أبدعها المعماري الشهير روبرت آدم. ويضم القصر مجموعة استثنائية من قطع الأثاث الفاخر التي صمّمها توماس شيبنديل إلى جانب أعمال نخبة من أشهر صانعي الأثاث الاسكتلنديين في القرن الثامن عشر.</p>',
    fieldEnglishResearch: '',
    fieldArabicResearch: '',
    headquartersEnglish: 'Dumfries House, Scotland',
    headquartersArabic: '',
    yearEstablished: 2025,
    yearClosed: '',
    order: '',
    status: 'published',
    createdOn: '3 October 2024',
    website: '',
    linkToPage: '',
    buttonText: '',
    twitter: '',
    facebook: '',
    instagram: '',
    linkedin: '',
    youtube: '',
    mainVideo: '',
    card: {
      url: '',
      alt: ''
    },
    hero: {
      url: '',
      alt: ''
    },
    openGraph: {
      url: '',
      alt: ''
    },
    logoSvgDark: {
      url: '',
      alt: ''
    },
    logoSvgOriginalRatio: {
      url: '',
      alt: ''
    },
    logoSvgSquareOverlay: {
      url: '',
      alt: ''
    },
    logoSvgLightOriginalRatio: {
      url: '',
      alt: ''
    },
    partners: [
      {
        name: "The King's Foundation",
        slug: 'the-kings-foundation',
        arabicName: ''
      },
      {
        name: 'Community Jameel',
        slug: 'community-jameel',
        arabicName: 'مجتمع جميل'
      }
    ],
    leadership: [
      {
        name: 'Khaled Azzam',
        slug: 'khaled-azzam',
        arabicName: ''
      }
    ],
    relatedProgrammes: [],
    features: [],
    impact01: '',
    impact01Title: '',
    impact01TitleArabic: '',
    impact02: '',
    impact02Title: '',
    impact02TitleArabic: '',
    impact03: '',
    impact03Title: '',
    impact03TitleArabic: '',
    impact04: '',
    impact04Title: '',
    impact04TitleArabic: '',
    impact05: '',
    impact05Title: '',
    impact05TitleArabic: '',
    impact06: '',
    impact06Title: '',
    impact06TitleArabic: '',
    latitude: '',
    longitude: '',
    colour: '',
    pushToGr: '',
    newsOnOff: false,
    tags: [],
    metaDescription: '',
    metaDescriptionArabic: ''
  },
  {
    id: 'be44464a-e266-4b8c-9a29-f6f179e7990a',
    slug: 'ankur',
    name: 'Ankur',
    nameArabic: 'برنامج أنكور',
    shortname: 'Ankur',
    shortNameArabic: 'برنامج أنكور',
    type: 'Programme',
    byline: 'Sowing seeds of climate resilience and economic empowerment',
    bylineArabic: '',
    text: '<p id="">Back-to-back cyclones between 2019-2022 made life for people in the Sundarbans difficult. From 2021 until 2024, the Ankur programme helped 10,000 families rebuild their lives through agricultural and poultry support, and in doing so, strengthened their resilience to future climate disasters.</p>',
    summaryLongEnglish:
      '<p id="">Back-to-back cyclones between 2019-2022 made life for people in the Sundarbans difficult. </p><p id="">From 2021 until 2024, the Ankur programme helped 10,000 families rebuild their lives through agricultural and poultry support, and in doing so, strengthened their resilience to future climate disasters.</p>',
    summaryLongArabic: '',
    fieldEnglishResearch: 'Capacity building',
    fieldArabicResearch: '',
    headquartersEnglish: 'Sundarbans, West Bengal, India',
    headquartersArabic: '',
    yearEstablished: 2021,
    yearClosed: 2024,
    order: '',
    status: 'published',
    createdOn: '26 October 2023',
    website: 'https://ankureducation.net/childrens-programme/',
    linkToPage: '',
    buttonText: 'visit rupantaran',
    twitter: 'https://twitter.com/rupantaran',
    facebook: 'https://www.facebook.com/Rupantaran/',
    instagram: '',
    linkedin: '',
    youtube: '',
    mainVideo: {
      url: 'https://www.youtube.com/watch?v=Mk12OIaap20',
      metadata: {
        html: '<iframe class="embedly-embed" src="//cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FMk12OIaap20%3Ffeature%3Doembed&display_name=YouTube&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DMk12OIaap20&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FMk12OIaap20%2Fhqdefault.jpg&key=96f1f04c5f4143bcb0f2e68c87d65feb&type=text%2Fhtml&schema=youtube" width="854" height="480" scrolling="no" title="YouTube embed" frameborder="0" allow="autoplay; fullscreen; encrypted-media; picture-in-picture;" allowfullscreen="true"></iframe>',
        type: 'video',
        title: 'Helping over 40,000 people rebuild their lives after cyclones',
        width: 854,
        height: 480,
        aspectRatio: 0,
        author_name: 'Community Jameel',
        description:
          'Community Jameel and the Rupantaran Foundation, a not for profit, non-governmental organisation in West Bengal, India, have joined forces in the Ankur programme, helping over 40,000 people in the Sundarbans region of West Bengal in India recover their livelihoods following catastrophic devastation caused by cyclones, and manage the rising threat of climate change.',
        provider_name: 'YouTube',
        thumbnail_url: 'https://i.ytimg.com/vi/Mk12OIaap20/hqdefault.jpg'
      }
    },
    card: {
      url: 'https://cdn.prod.website-files.com/612cede33b271d1b5bac6200/66f426d7b5bbb4111caa5a53_ANKUR_DSC01907%201-2.jpg',
      alt: ''
    },
    hero: {
      url: 'https://cdn.prod.website-files.com/612cede33b271d1b5bac6200/66f4272be66667b00a5e2b6a_ANKUR_DSC01907%201-1.jpg',
      alt: ''
    },
    openGraph: {
      url: 'https://cdn.prod.website-files.com/612cede33b271d1b5bac6200/66f426bd316ef1bed17afacf_ANKUR_DSC01907%201.jpg',
      alt: ''
    },
    logoSvgDark: {
      url: '',
      alt: ''
    },
    logoSvgOriginalRatio: {
      url: '',
      alt: ''
    },
    logoSvgSquareOverlay: {
      url: '',
      alt: ''
    },
    logoSvgLightOriginalRatio: {
      url: '',
      alt: ''
    },
    partners: [
      {
        name: 'Rupantaran Foundation',
        slug: 'rupantaran-foundation',
        arabicName: ''
      }
    ],
    leadership: [
      {
        name: 'Smita Sen',
        slug: 'smita-sen',
        arabicName: ''
      }
    ],
    relatedProgrammes: [],
    features: [],
    impact01: '10,000',
    impact01Title: 'families reached',
    impact01TitleArabic: '',
    impact02: '400',
    impact02Title: "women's collectives formed",
    impact02TitleArabic: '',
    impact03: '96%',
    impact03Title: 'reduction in food insecurity',
    impact03TitleArabic: '',
    impact04: '',
    impact04Title: '',
    impact04TitleArabic: '',
    impact05: '',
    impact05Title: '',
    impact05TitleArabic: '',
    impact06: '',
    impact06Title: '',
    impact06TitleArabic: '',
    latitude: '',
    longitude: '',
    colour: '',
    pushToGr: '',
    newsOnOff: false,
    tags: [],
    metaDescription: '',
    metaDescriptionArabic: ''
  },
  {
    id: '53e4b42d-21fc-44b6-81ea-15aa33c2e8e4',
    slug: 'jameel-c40-urban-planning-climate-labs',
    name: 'Jameel C40 Urban Planning Climate Labs',
    nameArabic: 'مختبرات جميل C40 للتخطيط العمراني والمناخية',
    shortname: 'Jameel C40 Urban Planning Climate Labs',
    shortNameArabic: 'مختبرات جميل C40 للتخطيط العمراني والمناخية',
    type: 'Lab',
    byline:
      'Assisting rapidly-growing cities to align climate action with urban planning',
    bylineArabic:
      'مساعدة المدن سريعة النمو على مواءمة العمل المناخي مع التخطيط الحضري',
    text: '<p id="">The Jameel C40 Urban Planning Climate Labs assist rapidly growing cities – including Chennai, India, and Amman, Jordan – in merging climate action with urban planning. The labs aim to refine city plans to align with climate goals and develop sustainable, low-carbon urban spaces as models. The labs also aim to provide a blueprint for cities to seamlessly integrate climate considerations into their planning processes.</p>',
    summaryLongEnglish:
      '<p id="">The Jameel C40 Urban Planning Climate Labs assist rapidly growing cities – including Chennai, India, and Amman, Jordan – in merging climate action with urban planning. </p><p id="">The labs aim to refine city plans to align with climate goals and develop sustainable, low-carbon urban spaces as models. </p><p id="">The labs also aim to provide a blueprint for cities to seamlessly integrate climate considerations into their planning processes.</p>',
    summaryLongArabic:
      '<p id="">تساعد مختبرات جميل سي 40 للمناخ للتخطيط الحضري المدن سريعة النمو - بما في ذلك تشيناي، الهند، وعمان، الأردن - في دمج العمل المناخي مع التخطيط الحضري. وهي تهدف إلى تحسين خطط المدن لتتوافق مع الأهداف المناخية وتطوير مساحات حضرية مستدامة ومنخفضة الكربون كنماذج. وتهدف المختبرات أيضًا إلى توفير مخطط للمدن لدمج الاعتبارات المناخية بسلاسة في عمليات التخطيط الخاصة بها.</p>',
    fieldEnglishResearch: 'Urban planning\nClimate resilience',
    fieldArabicResearch: 'التخطيط العمراني\nمرونة المناخ',
    headquartersEnglish: 'Chennai, India & Amman, Jordan',
    headquartersArabic: 'عالمي',
    yearEstablished: 2024,
    yearClosed: '',
    order: 12,
    status: 'published',
    createdOn: '5 October 2023',
    website: '',
    linkToPage: '',
    buttonText: '',
    twitter: '',
    facebook: '',
    instagram: '',
    linkedin: '',
    youtube: '',
    mainVideo: {
      url: 'https://www.youtube.com/watch?v=46WXtuetDrA',
      metadata: {
        html: '<iframe class="embedly-embed" src="//cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2F46WXtuetDrA%3Ffeature%3Doembed&display_name=YouTube&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D46WXtuetDrA&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2F46WXtuetDrA%2Fhqdefault.jpg&key=96f1f04c5f4143bcb0f2e68c87d65feb&type=text%2Fhtml&schema=youtube" width="854" height="480" scrolling="no" title="YouTube embed" frameborder="0" allow="autoplay; fullscreen; encrypted-media; picture-in-picture;" allowfullscreen="true"></iframe>',
        type: 'video',
        title: 'Transforming urban planning and climate action in Chennai',
        width: 854,
        height: 480,
        aspectRatio: 0,
        author_name: 'Community Jameel',
        description:
          'The Jameel C40 Urban Planning Climate Lab in Chennai is helping the Chennai Metropolitan Development Authority (CMDA) revise its master plan for the city to better integrate climate objectives and adapt to climate risks. The Jameel C40 Urban Planning Climate Labs support fast-growing cities in South and West Asia by integrating climate action planning with urban planning.',
        provider_name: 'YouTube',
        thumbnail_url: 'https://i.ytimg.com/vi/46WXtuetDrA/hqdefault.jpg'
      }
    },
    card: {
      url: 'https://cdn.prod.website-files.com/612cede33b271d1b5bac6200/667d73fef5e4e3e59e8bd377_C40JAMEEL_HERO_1x1.jpg',
      alt: ''
    },
    hero: {
      url: 'https://cdn.prod.website-files.com/612cede33b271d1b5bac6200/667d73fb644c6219654b3894_C40JAMEEL_HERO_16x9.jpg',
      alt: ''
    },
    openGraph: {
      url: 'https://cdn.prod.website-files.com/612cede33b271d1b5bac6200/667d73f93f76d81e5fbda2f4_C40JAMEEL_HERO_OG.jpg',
      alt: ''
    },
    logoSvgDark: {
      url: '',
      alt: ''
    },
    logoSvgOriginalRatio: {
      url: '',
      alt: ''
    },
    logoSvgSquareOverlay: {
      url: '',
      alt: ''
    },
    logoSvgLightOriginalRatio: {
      url: '',
      alt: ''
    },
    partners: [
      {
        name: 'C40',
        slug: 'c40',
        arabicName: ''
      }
    ],
    leadership: [
      {
        name: 'Shruti Narayan',
        slug: 'shruti-narayan',
        arabicName: ''
      }
    ],
    relatedProgrammes: [
      {
        name: 'N/A',
        slug: 'N/A',
        arabicName: 'N/A'
      },
      {
        name: 'J-PAL Air and Water Labs',
        slug: 'jpal-air-and-water-labs',
        arabicName: 'معامل J-PAL للهواء والماء'
      }
    ],
    features: [],
    impact01: '',
    impact01Title: '',
    impact01TitleArabic: '',
    impact02: '',
    impact02Title: '',
    impact02TitleArabic: '',
    impact03: '',
    impact03Title: '',
    impact03TitleArabic: '',
    impact04: '',
    impact04Title: '',
    impact04TitleArabic: '',
    impact05: '',
    impact05Title: '',
    impact05TitleArabic: '',
    impact06: '',
    impact06Title: '',
    impact06TitleArabic: '',
    latitude: '',
    longitude: '',
    colour: '',
    pushToGr: '',
    newsOnOff: false,
    tags: [],
    metaDescription: '',
    metaDescriptionArabic: ''
  },
  {
    id: 'a5472380-42a5-4398-99e7-e2c1a56752a5',
    slug: 'jpal-air-and-water-labs',
    name: 'J-PAL Air and Water Labs',
    nameArabic: 'معامل J-PAL للهواء والماء',
    shortname: 'J-PAL AWL',
    shortNameArabic: 'J-PAL AWL',
    type: 'Programme',
    byline:
      "Evidence-based solutions for the world's most pressing air and water challenges",
    bylineArabic:
      'حلول قائمة على الأدلة لتحديات الهواء والماء الأكثر إلحاحًا في العالم',
    text: '<p id="">J-PAL\'s Air and Water Labs address air and water issues in Africa, the Middle East and North Africa (MENA), and South Asia by co-generating evidence-based solutions with government partners. These regions face severe air and water crises, impacting health and longevity. The labs enhance policymakers\' access to data, co-design targeted policies, and support effective solutions through pilots and evaluations. Initiatives include SARWA in India, WAE in South Africa, and HAPIE in Egypt, aiming to improve clean air and water access.</p>',
    summaryLongEnglish:
      '<p id="">J-PAL\'s Air and Water Labs address air and water issues in Africa, the Middle East and North Africa (MENA), and South Asia by co-generating evidence-based solutions with government partners. </p><p id="">These regions face severe air and water crises, impacting health and longevity. The labs enhance policymakers\' access to data, co-design targeted policies, and support effective solutions through pilots and evaluations. </p><p id="">Initiatives include SARWA in India, WAE in South Africa, and HAPIE in Egypt, aiming to improve clean air and water access.</p>',
    summaryLongArabic:
      '<p id="">تعالج مختبرات الهواء والماء التابعة لمعمل J-PAL قضايا الهواء والماء في أفريقيا والشرق الأوسط وشمال أفريقيا (MENA) وجنوب آسيا من خلال المشاركة في إيجاد حلول قائمة على الأدلة مع الشركاء الحكوميين. وتواجه هذه المناطق أزمات حادة في الهواء والماء، مما يؤثر على الصحة وطول العمر. تعمل المختبرات على تعزيز وصول صناع السياسات إلى البيانات، والمشاركة في تصميم السياسات المستهدفة، ودعم الحلول الفعالة من خلال التجارب والتقييمات. وتشمل المبادرات SARWA في الهند، وWAE في جنوب أفريقيا، وHAPIE في مصر، بهدف تحسين الوصول إلى الهواء النظيف والمياه.</p>',
    fieldEnglishResearch: 'Water access, clean air, informing policy\n',
    fieldArabicResearch: 'الوصول إلى المياه\nهواء نظيف\nإعلام السياسة',
    headquartersEnglish: 'Global',
    headquartersArabic: 'عالمي',
    yearEstablished: 2024,
    yearClosed: '',
    order: 13,
    status: 'published',
    createdOn: '14 September 2023',
    website: 'https://www.povertyactionlab.org/page/air-and-water-labs',
    linkToPage: '/programmes/air-and-water-labs',
    buttonText: 'visit website',
    twitter: '',
    facebook: '',
    instagram: '',
    linkedin: '',
    youtube: '',
    mainVideo: {
      url: 'https://www.youtube.com/watch?v=0g31Hu7RRrI',
      metadata: {
        html: '<iframe class="embedly-embed" src="//cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2F0g31Hu7RRrI%3Ffeature%3Doembed&display_name=YouTube&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D0g31Hu7RRrI&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2F0g31Hu7RRrI%2Fhqdefault.jpg&key=96f1f04c5f4143bcb0f2e68c87d65feb&type=text%2Fhtml&schema=youtube" width="854" height="480" scrolling="no" title="YouTube embed" frameborder="0" allow="autoplay; fullscreen; encrypted-media; picture-in-picture;" allowfullscreen="true"></iframe>',
        type: 'video',
        title:
          'Embedding evidence and innovation in climate policymaking | Climate labs with J-PAL and C40',
        width: 854,
        height: 480,
        aspectRatio: 0,
        author_name: 'Community Jameel',
        description:
          'Embedded with government policymakers in Egypt, India, Jordan and South Africa, Community Jameel, C40 Cities and the Abdul Latif Jameel Poverty Action Lab (J-PAL) operate a network of climate labs pioneering innovative, evidence-based strategies to tackling climate change. The climate labs work with national, state, and city government teams to foster evidence-based and innovative strategies in tackling climate change.',
        provider_name: 'YouTube',
        thumbnail_url: 'https://i.ytimg.com/vi/0g31Hu7RRrI/hqdefault.jpg'
      }
    },
    card: {
      url: 'https://cdn.prod.website-files.com/612cede33b271d1b5bac6200/667d1f5b97db5ea8bc016900_AIR_WATER_LAB_HERO_1x1.jpg',
      alt: ''
    },
    hero: {
      url: 'https://cdn.prod.website-files.com/612cede33b271d1b5bac6200/667d1f59af109fcfacc9dfdf_AIR_WATER_LAB_HERO_16x9.jpg',
      alt: ''
    },
    openGraph: {
      url: 'https://cdn.prod.website-files.com/612cede33b271d1b5bac6200/667d1f56f5cd6d3a8e9f0869_AIR_WATER_LAB_HERO_OG.jpg',
      alt: ''
    },
    logoSvgDark: {
      url: 'https://cdn.prod.website-files.com/612cede33b271d1b5bac6200/667d1fa05b3c9f28de370ca1_AIR_WATER_LAB_EVALUATION_LAB_DARK_1000px.svg',
      alt: ''
    },
    logoSvgOriginalRatio: {
      url: 'https://cdn.prod.website-files.com/612cede33b271d1b5bac6200/667d1f9851cd6b81818a837b_AIR_WATER_LAB_ORIGINAL_DARK_SVG.svg',
      alt: ''
    },
    logoSvgSquareOverlay: {
      url: 'https://cdn.prod.website-files.com/612cede33b271d1b5bac6200/667d1f9ecfed335bea22690e_AIR_WATER_LAB_LIGHT_1000px.svg',
      alt: ''
    },
    logoSvgLightOriginalRatio: {
      url: 'https://cdn.prod.website-files.com/612cede33b271d1b5bac6200/667d1f9b8f08a445ae9523a0_AIR_WATER_LAB_LIGHT_SVG.svg',
      alt: ''
    },
    partners: [],
    leadership: [
      {
        name: 'Michael Greenstone',
        slug: 'michael-greenstone',
        arabicName: ''
      },
      {
        name: 'Namrata Kala',
        slug: 'namrata-kala',
        arabicName: ''
      },
      {
        name: 'Kelsey Jack',
        slug: 'kelsey-jack',
        arabicName: ''
      },
      {
        name: 'Kyle Emerick',
        slug: 'kyle-emerick',
        arabicName: ''
      }
    ],
    relatedProgrammes: [
      {
        name: 'J-PAL MENA',
        slug: 'jameel-poverty-action-lab-middle-east-and-north-africa',
        arabicName: ''
      },
      {
        name: 'Abdul Latif Jameel Poverty Action Lab',
        slug: 'j-pal',
        arabicName: 'معمل عبد اللطيف جميل لمكافحة الفقر'
      }
    ],
    features: [],
    impact01: '3',
    impact01Title: 'labs established',
    impact01TitleArabic: '',
    impact02: '260M ',
    impact02Title: 'people targeted to reach',
    impact02TitleArabic: '',
    impact03: '',
    impact03Title: '',
    impact03TitleArabic: '',
    impact04: '',
    impact04Title: '',
    impact04TitleArabic: '',
    impact05: '',
    impact05Title: '',
    impact05TitleArabic: '',
    impact06: '',
    impact06Title: '',
    impact06TitleArabic: '',
    latitude: '',
    longitude: '',
    colour: '',
    pushToGr: '',
    newsOnOff: false,
    tags: [],
    metaDescription: '',
    metaDescriptionArabic: ''
  },
  {
    id: '6f7e8d9c-ab12-4c34-89ef-12ab34cd56ef',
    slug: 'jameel-house-of-traditional-arts-at-the-prince-school-of-traditional-arts',
    name: "Jameel House of Traditional Arts at the Prince's School of Traditional Arts",
    nameArabic: 'بيت جميل للفنون التراثية في مدرسة الأمير للفنون التراثية',
    shortname: 'Jameel House at PSTA',
    shortNameArabic: 'بيت جميل في PSTA',
    type: 'Programme',
    byline:
      'Preserving and teaching traditional arts and crafts from around the world',
    bylineArabic:
      'الحفاظ على الفنون والحرف التراثية من جميع أنحاء العالم وتعليمها',
    text: "<p>The Jameel House of Traditional Arts at the Prince's School of Traditional Arts offers courses and workshops in traditional arts and crafts from around the world, including Islamic art, geometric patterns, and calligraphy.</p>",
    summaryLongEnglish:
      "<p>Located in London, the Jameel House of Traditional Arts at the Prince's School of Traditional Arts is dedicated to preserving and teaching traditional arts and crafts from around the world. The programme offers a range of courses and workshops in subjects including Islamic art, geometric patterns, calligraphy, and traditional crafts.</p>",
    summaryLongArabic:
      '<p>يقع بيت جميل للفنون التراثية في مدرسة الأمير للفنون التراثية في لندن، وهو مخصص للحفاظ على الفنون والحرف التراثية من جميع أنحاء العالم وتعليمها. يقدم البرنامج مجموعة من الدورات وورش العمل في مواضيع تشمل الفن الإسلامي والأنماط الهندسية والخط والحرف التقليدية.</p>',
    fieldEnglishResearch: 'Traditional arts education',
    fieldArabicResearch: 'تعليم الفنون التراثية',
    headquartersEnglish: 'London, UK',
    headquartersArabic: 'لندن، المملكة المتحدة',
    yearEstablished: 2005,
    yearClosed: '',
    order: '',
    status: 'published',
    createdOn: '1 January 2020',
    website: 'https://www.princes-school-of-traditional-arts.org',
    linkToPage: '',
    buttonText: 'visit website',
    twitter: '',
    facebook: '',
    instagram: '',
    linkedin: '',
    youtube: '',
    mainVideo: '',
    card: { url: '', alt: '' },
    hero: { url: '', alt: '' },
    openGraph: { url: '', alt: '' },
    logoSvgDark: { url: '', alt: '' },
    logoSvgOriginalRatio: { url: '', alt: '' },
    logoSvgSquareOverlay: { url: '', alt: '' },
    logoSvgLightOriginalRatio: { url: '', alt: '' },
    partners: [
      {
        name: "The King's Foundation",
        slug: 'the-kings-foundation',
        arabicName: ''
      },
      {
        name: 'Community Jameel',
        slug: 'community-jameel',
        arabicName: 'مجتمع جميل'
      }
    ],
    leadership: [],
    relatedProgrammes: [],
    features: [],
    impact01: '',
    impact01Title: '',
    impact01TitleArabic: '',
    impact02: '',
    impact02Title: '',
    impact02TitleArabic: '',
    impact03: '',
    impact03Title: '',
    impact03TitleArabic: '',
    impact04: '',
    impact04Title: '',
    impact04TitleArabic: '',
    impact05: '',
    impact05Title: '',
    impact05TitleArabic: '',
    impact06: '',
    impact06Title: '',
    impact06TitleArabic: '',
    latitude: '',
    longitude: '',
    colour: '',
    pushToGr: '',
    newsOnOff: false,
    tags: [],
    metaDescription: '',
    metaDescriptionArabic: ''
  },
  {
    id: '7g8f9e0d-bc23-5d45-9a01-23bc45de67f0',
    slug: 'jameel-poverty-action-lab-middle-east-and-north-africa',
    name: 'J-PAL MENA',
    nameArabic:
      'معمل عبد اللطيف جميل لمكافحة الفقر - الشرق الأوسط وشمال أفريقيا',
    shortname: 'J-PAL MENA',
    shortNameArabic: 'J-PAL MENA',
    type: 'Lab',
    byline:
      'Evidence-based policy solutions to reduce poverty in the Middle East and North Africa',
    bylineArabic:
      'حلول سياسية قائمة على الأدلة لتقليل الفقر في الشرق الأوسط وشمال أفريقيا',
    text: '<p>J-PAL MENA conducts randomized evaluations and policy outreach to reduce poverty in the Middle East and North Africa region.</p>',
    summaryLongEnglish:
      '<p>The Abdul Latif Jameel Poverty Action Lab Middle East and North Africa (J-PAL MENA) is a regional office that conducts randomized evaluations of social programs and policies to reduce poverty in the MENA region. Based at the American University of Cairo, J-PAL MENA works with governments, NGOs, and international organizations to design, implement, and scale evidence-based programs.</p>',
    summaryLongArabic:
      '<p>معمل عبد اللطيف جميل لمكافحة الفقر في الشرق الأوسط وشمال أفريقيا (J-PAL MENA) هو مكتب إقليمي يقوم بإجراء تقييمات عشوائية للبرامج والسياسات الاجتماعية لتقليل الفقر في منطقة الشرق الأوسط وشمال أفريقيا. يقع المكتب في الجامعة الأمريكية بالقاهرة، ويعمل J-PAL MENA مع الحكومات والمنظمات غير الحكومية والمنظمات الدولية لتصميم وتنفيذ وتوسيع البرامج القائمة على الأدلة.</p>',
    fieldEnglishResearch: 'Poverty reduction, policy evaluation',
    fieldArabicResearch: 'تقليل الفقر، تقييم السياسات',
    headquartersEnglish: 'Cairo, Egypt',
    headquartersArabic: 'القاهرة، مصر',
    yearEstablished: 2009,
    yearClosed: '',
    order: '',
    status: 'published',
    createdOn: '1 January 2020',
    website: 'https://www.povertyactionlab.org/mena',
    linkToPage: '',
    buttonText: 'visit website',
    twitter: '',
    facebook: '',
    instagram: '',
    linkedin: '',
    youtube: '',
    mainVideo: '',
    card: { url: '', alt: '' },
    hero: { url: '', alt: '' },
    openGraph: { url: '', alt: '' },
    logoSvgDark: { url: '', alt: '' },
    logoSvgOriginalRatio: { url: '', alt: '' },
    logoSvgSquareOverlay: { url: '', alt: '' },
    logoSvgLightOriginalRatio: { url: '', alt: '' },
    partners: [
      {
        name: 'American University of Cairo',
        slug: 'american-university-of-cairo',
        arabicName: ''
      }
    ],
    leadership: [
      { name: 'Selim Gulesci', slug: 'selim-gulesci', arabicName: '' }
    ],
    relatedProgrammes: [
      {
        name: 'Abdul Latif Jameel Poverty Action Lab',
        slug: 'j-pal',
        arabicName: 'معمل عبد اللطيف جميل لمكافحة الفقر'
      }
    ],
    features: [],
    impact01: '',
    impact01Title: '',
    impact01TitleArabic: '',
    impact02: '',
    impact02Title: '',
    impact02TitleArabic: '',
    impact03: '',
    impact03Title: '',
    impact03TitleArabic: '',
    impact04: '',
    impact04Title: '',
    impact04TitleArabic: '',
    impact05: '',
    impact05Title: '',
    impact05TitleArabic: '',
    impact06: '',
    impact06Title: '',
    impact06TitleArabic: '',
    latitude: '',
    longitude: '',
    colour: '',
    pushToGr: '',
    newsOnOff: false,
    tags: [],
    metaDescription: '',
    metaDescriptionArabic: ''
  },
  {
    id: '8h9g0f1e-cd34-6e56-ab12-34cd56ef78g1',
    slug: 'j-pal',
    name: 'Abdul Latif Jameel Poverty Action Lab',
    nameArabic: 'معمل عبد اللطيف جميل لمكافحة الفقر',
    shortname: 'J-PAL',
    shortNameArabic: 'J-PAL',
    type: 'Lab',
    byline: 'Reducing poverty worldwide through evidence-based policy',
    bylineArabic:
      'تقليل الفقر في جميع أنحاء العالم من خلال السياسات القائمة على الأدلة',
    text: '<p>The Abdul Latif Jameel Poverty Action Lab (J-PAL) is a global research center working to reduce poverty by ensuring that policy is informed by scientific evidence.</p>',
    summaryLongEnglish:
      '<p>The Abdul Latif Jameel Poverty Action Lab (J-PAL) is a global research center working to reduce poverty by ensuring that policy is informed by scientific evidence. Anchored by a network of 234 affiliated professors at universities around the world, J-PAL conducts randomized impact evaluations to answer critical questions in the fight against poverty.</p>',
    summaryLongArabic:
      '<p>معمل عبد اللطيف جميل لمكافحة الفقر (J-PAL) هو مركز بحثي عالمي يعمل على تقليل الفقر من خلال ضمان أن تكون السياسة مدعومة بالأدلة العلمية. يرتكز المعمل على شبكة من 234 أستاذاً منتسباً في جامعات حول العالم، ويقوم J-PAL بإجراء تقييمات الأثر العشوائية للإجابة على الأسئلة الحرجة في مكافحة الفقر.</p>',
    fieldEnglishResearch: 'Poverty reduction, development economics',
    fieldArabicResearch: 'تقليل الفقر، اقتصاد التنمية',
    headquartersEnglish: 'Cambridge, Massachusetts, USA',
    headquartersArabic: 'كامبريدج، ماساتشوستس، الولايات المتحدة الأمريكية',
    yearEstablished: 2003,
    yearClosed: '',
    order: '',
    status: 'published',
    createdOn: '1 January 2020',
    website: 'https://www.povertyactionlab.org',
    linkToPage: '',
    buttonText: 'visit website',
    twitter: '',
    facebook: '',
    instagram: '',
    linkedin: '',
    youtube: '',
    mainVideo: '',
    card: { url: '', alt: '' },
    hero: { url: '', alt: '' },
    openGraph: { url: '', alt: '' },
    logoSvgDark: { url: '', alt: '' },
    logoSvgOriginalRatio: { url: '', alt: '' },
    logoSvgSquareOverlay: { url: '', alt: '' },
    logoSvgLightOriginalRatio: { url: '', alt: '' },
    partners: [{ name: 'MIT', slug: 'mit', arabicName: '' }],
    leadership: [
      { name: 'Esther Duflo', slug: 'esther-duflo', arabicName: '' },
      { name: 'Abhijit Banerjee', slug: 'abhijit-banerjee', arabicName: '' }
    ],
    relatedProgrammes: [],
    features: [],
    impact01: '1000+',
    impact01Title: 'randomized evaluations',
    impact01TitleArabic: '',
    impact02: '400M+',
    impact02Title: 'people reached',
    impact02TitleArabic: '',
    impact03: '',
    impact03Title: '',
    impact03TitleArabic: '',
    impact04: '',
    impact04Title: '',
    impact04TitleArabic: '',
    impact05: '',
    impact05Title: '',
    impact05TitleArabic: '',
    impact06: '',
    impact06Title: '',
    impact06TitleArabic: '',
    latitude: '',
    longitude: '',
    colour: '',
    pushToGr: '',
    newsOnOff: false,
    tags: [],
    metaDescription: '',
    metaDescriptionArabic: ''
  },
  {
    id: '9i0h1g2f-de45-7f67-bc23-45de67f89h02',
    slug: 'jameel-observatory-crewsnet',
    name: 'Jameel Observatory CREWSnet',
    nameArabic: 'مرصد جميل CREWSnet',
    shortname: 'CREWSnet',
    shortNameArabic: 'CREWSnet',
    type: 'Observatory',
    byline: 'Early warning systems for climate-related extreme weather events',
    bylineArabic: 'أنظمة إنذار مبكر للأحداث الجوية المتطرفة المرتبطة بالمناخ',
    text: '<p>The Jameel Observatory CREWSnet develops early warning systems for climate-related extreme weather events to help communities prepare and respond to natural disasters.</p>',
    summaryLongEnglish:
      '<p>The Jameel Observatory CREWSnet is dedicated to developing and implementing early warning systems for climate-related extreme weather events. By leveraging advanced technology and data analytics, CREWSnet helps communities, governments, and organizations prepare for and respond to natural disasters such as floods, droughts, and severe storms.</p>',
    summaryLongArabic:
      '<p>مرصد جميل CREWSnet مخصص لتطوير وتنفيذ أنظمة الإنذار المبكر للأحداث الجوية المتطرفة المرتبطة بالمناخ. من خلال الاستفادة من التكنولوجيا المتقدمة وتحليل البيانات، يساعد CREWSnet المجتمعات والحكومات والمنظمات على الاستعداد للكوارث الطبيعية والاستجابة لها مثل الفيضانات والجفاف والعواصف الشديدة.</p>',
    fieldEnglishResearch: 'Climate resilience, early warning systems',
    fieldArabicResearch: 'مرونة المناخ، أنظمة الإنذار المبكر',
    headquartersEnglish: 'Global',
    headquartersArabic: 'عالمي',
    yearEstablished: 2022,
    yearClosed: '',
    order: '',
    status: 'published',
    createdOn: '1 January 2023',
    website: 'https://crews-net.org',
    linkToPage: '',
    buttonText: 'visit website',
    twitter: '',
    facebook: '',
    instagram: '',
    linkedin: '',
    youtube: '',
    mainVideo: '',
    card: { url: '', alt: '' },
    hero: { url: '', alt: '' },
    openGraph: { url: '', alt: '' },
    logoSvgDark: { url: '', alt: '' },
    logoSvgOriginalRatio: { url: '', alt: '' },
    logoSvgSquareOverlay: { url: '', alt: '' },
    logoSvgLightOriginalRatio: { url: '', alt: '' },
    partners: [],
    leadership: [],
    relatedProgrammes: [],
    features: [],
    impact01: '',
    impact01Title: '',
    impact01TitleArabic: '',
    impact02: '',
    impact02Title: '',
    impact02TitleArabic: '',
    impact03: '',
    impact03Title: '',
    impact03TitleArabic: '',
    impact04: '',
    impact04Title: '',
    impact04TitleArabic: '',
    impact05: '',
    impact05Title: '',
    impact05TitleArabic: '',
    impact06: '',
    impact06Title: '',
    impact06TitleArabic: '',
    latitude: '',
    longitude: '',
    colour: '',
    pushToGr: '',
    newsOnOff: false,
    tags: [],
    metaDescription: '',
    metaDescriptionArabic: ''
  },
  {
    id: '0j1i2h3g-ef56-8g78-cd34-56ef78g90j13',
    slug: 'jameel-clinic',
    name: 'Jameel Clinic',
    nameArabic: 'عيادة جميل',
    shortname: 'Jameel Clinic',
    shortNameArabic: 'عيادة جميل',
    type: 'Clinic',
    byline: 'Machine learning for healthcare and climate solutions',
    bylineArabic: 'التعلم الآلي لحلول الرعاية الصحية والمناخ',
    text: '<p>The Jameel Clinic uses machine learning and artificial intelligence to advance healthcare and climate solutions, focusing on applications that can benefit underserved populations.</p>',
    summaryLongEnglish:
      '<p>The Jameel Clinic for Machine Learning in Health at MIT focuses on developing machine learning technologies to improve healthcare outcomes and address climate challenges. The clinic works on projects ranging from medical imaging and drug discovery to climate modeling and environmental monitoring, with a particular emphasis on solutions that can benefit underserved populations globally.</p>',
    summaryLongArabic:
      '<p>تركز عيادة جميل للتعلم الآلي في الصحة في معهد ماساتشوستس للتكنولوجيا على تطوير تقنيات التعلم الآلي لتحسين نتائج الرعاية الصحية ومعالجة التحديات المناخية. تعمل العيادة على مشاريع تتراوح من التصوير الطبي واكتشاف الأدوية إلى النمذجة المناخية والمراقبة البيئية، مع التركيز بشكل خاص على الحلول التي يمكن أن تفيد السكان المحرومين عالمياً.</p>',
    fieldEnglishResearch: 'Machine learning, healthcare, climate science',
    fieldArabicResearch: 'التعلم الآلي، الرعاية الصحية، علوم المناخ',
    headquartersEnglish: 'Cambridge, Massachusetts, USA',
    headquartersArabic: 'كامبريدج، ماساتشوستس، الولايات المتحدة الأمريكية',
    yearEstablished: 2018,
    yearClosed: '',
    order: '',
    status: 'published',
    createdOn: '1 January 2020',
    website: 'https://www.jameel-clinic.org',
    linkToPage: '',
    buttonText: 'visit website',
    twitter: '',
    facebook: '',
    instagram: '',
    linkedin: '',
    youtube: '',
    mainVideo: '',
    card: { url: '', alt: '' },
    hero: { url: '', alt: '' },
    openGraph: { url: '', alt: '' },
    logoSvgDark: { url: '', alt: '' },
    logoSvgOriginalRatio: { url: '', alt: '' },
    logoSvgSquareOverlay: { url: '', alt: '' },
    logoSvgLightOriginalRatio: { url: '', alt: '' },
    partners: [{ name: 'MIT', slug: 'mit', arabicName: '' }],
    leadership: [
      { name: 'Regina Barzilay', slug: 'regina-barzilay', arabicName: '' }
    ],
    relatedProgrammes: [],
    features: [],
    impact01: '',
    impact01Title: '',
    impact01TitleArabic: '',
    impact02: '',
    impact02Title: '',
    impact02TitleArabic: '',
    impact03: '',
    impact03Title: '',
    impact03TitleArabic: '',
    impact04: '',
    impact04Title: '',
    impact04TitleArabic: '',
    impact05: '',
    impact05Title: '',
    impact05TitleArabic: '',
    impact06: '',
    impact06Title: '',
    impact06TitleArabic: '',
    latitude: '',
    longitude: '',
    colour: '',
    pushToGr: '',
    newsOnOff: false,
    tags: [],
    metaDescription: '',
    metaDescriptionArabic: ''
  },
  {
    id: '1k2j3i4h-fg67-9h89-de45-67fg89h01k24',
    slug: 'jameel-water-and-food-systems-lab',
    name: 'Jameel Water and Food Systems Lab',
    nameArabic: 'معمل جميل لأنظمة المياه والغذاء',
    shortname: 'J-WAFS',
    shortNameArabic: 'J-WAFS',
    type: 'Lab',
    byline: 'Solutions for global water and food security challenges',
    bylineArabic: 'حلول لتحديات الأمن المائي والغذائي العالمي',
    text: '<p>The Jameel Water and Food Systems Lab (J-WAFS) at MIT works to develop technologies and solutions to address global water and food security challenges.</p>',
    summaryLongEnglish:
      '<p>The Abdul Latif Jameel Water and Food Systems Lab (J-WAFS) at MIT is dedicated to developing technologies and solutions to address global water and food security challenges. Through research, innovation, and partnership, J-WAFS works to ensure that all people have access to sufficient, safe, and nutritious food and clean water.</p>',
    summaryLongArabic:
      '<p>معمل عبد اللطيف جميل لأنظمة المياه والغذاء (J-WAFS) في معهد ماساتشوستس للتكنولوجيا مخصص لتطوير التقنيات والحلول لمعالجة تحديات الأمن المائي والغذائي العالمي. من خلال البحث والابتكار والشراكة، يعمل J-WAFS على ضمان حصول جميع الناس على غذاء كافٍ وآمن ومغذٍ ومياه نظيفة.</p>',
    fieldEnglishResearch: 'Water security, food systems, sustainability',
    fieldArabicResearch: 'أمن المياه، أنظمة الغذاء، الاستدامة',
    headquartersEnglish: 'Cambridge, Massachusetts, USA',
    headquartersArabic: 'كامبريدج، ماساتشوستس، الولايات المتحدة الأمريكية',
    yearEstablished: 2014,
    yearClosed: '',
    order: '',
    status: 'published',
    createdOn: '1 January 2020',
    website: 'https://jwafs.mit.edu',
    linkToPage: '',
    buttonText: 'visit website',
    twitter: '',
    facebook: '',
    instagram: '',
    linkedin: '',
    youtube: '',
    mainVideo: '',
    card: { url: '', alt: '' },
    hero: { url: '', alt: '' },
    openGraph: { url: '', alt: '' },
    logoSvgDark: { url: '', alt: '' },
    logoSvgOriginalRatio: { url: '', alt: '' },
    logoSvgSquareOverlay: { url: '', alt: '' },
    logoSvgLightOriginalRatio: { url: '', alt: '' },
    partners: [{ name: 'MIT', slug: 'mit', arabicName: '' }],
    leadership: [
      { name: 'John H. Lienhard V', slug: 'john-lienhard', arabicName: '' }
    ],
    relatedProgrammes: [],
    features: [],
    impact01: '150+',
    impact01Title: 'research projects funded',
    impact01TitleArabic: '',
    impact02: '50+',
    impact02Title: 'startups launched',
    impact02TitleArabic: '',
    impact03: '',
    impact03Title: '',
    impact03TitleArabic: '',
    impact04: '',
    impact04Title: '',
    impact04TitleArabic: '',
    impact05: '',
    impact05Title: '',
    impact05TitleArabic: '',
    impact06: '',
    impact06Title: '',
    impact06TitleArabic: '',
    latitude: '',
    longitude: '',
    colour: '',
    pushToGr: '',
    newsOnOff: false,
    tags: [],
    metaDescription: '',
    metaDescriptionArabic: ''
  },
  {
    id: '2l3k4j5i-gh78-0i90-ef56-78gh90i12l35',
    slug: 'jameel-observatory',
    name: 'Jameel Observatory',
    nameArabic: 'مرصد جميل',
    shortname: 'Jameel Observatory',
    shortNameArabic: 'مرصد جميل',
    type: 'Observatory',
    byline: 'Data-driven insights for climate resilience and food security',
    bylineArabic: 'رؤى مدفوعة بالبيانات لمرونة المناخ وأمن الغذاء',
    text: '<p>The Jameel Observatory provides data-driven insights to support climate resilience and food security initiatives across the world.</p>',
    summaryLongEnglish:
      '<p>The Jameel Observatory leverages satellite data, machine learning, and advanced analytics to provide insights that support climate resilience and food security initiatives. The observatory works with governments, NGOs, and international organizations to monitor environmental changes, assess risks, and inform decision-making for sustainable development.</p>',
    summaryLongArabic:
      '<p>يستفيد مرصد جميل من بيانات الأقمار الصناعية والتعلم الآلي والتحليلات المتقدمة لتوفير رؤى تدعم مبادرات مرونة المناخ وأمن الغذاء. يعمل المرصد مع الحكومات والمنظمات غير الحكومية والمنظمات الدولية لمراقبة التغيرات البيئية وتقييم المخاطر وإعلام صنع القرار للتنمية المستدامة.</p>',
    fieldEnglishResearch: 'Climate monitoring, data analytics, sustainability',
    fieldArabicResearch: 'مراقبة المناخ، تحليل البيانات، الاستدامة',
    headquartersEnglish: 'Global',
    headquartersArabic: 'عالمي',
    yearEstablished: 2021,
    yearClosed: '',
    order: '',
    status: 'published',
    createdOn: '1 January 2022',
    website: 'https://www.jameelobservatory.org',
    linkToPage: '',
    buttonText: 'visit website',
    twitter: '',
    facebook: '',
    instagram: '',
    linkedin: '',
    youtube: '',
    mainVideo: '',
    card: { url: '', alt: '' },
    hero: { url: '', alt: '' },
    openGraph: { url: '', alt: '' },
    logoSvgDark: { url: '', alt: '' },
    logoSvgOriginalRatio: { url: '', alt: '' },
    logoSvgSquareOverlay: { url: '', alt: '' },
    logoSvgLightOriginalRatio: { url: '', alt: '' },
    partners: [],
    leadership: [],
    relatedProgrammes: [],
    features: [],
    impact01: '',
    impact01Title: '',
    impact01TitleArabic: '',
    impact02: '',
    impact02Title: '',
    impact02TitleArabic: '',
    impact03: '',
    impact03Title: '',
    impact03TitleArabic: '',
    impact04: '',
    impact04Title: '',
    impact04TitleArabic: '',
    impact05: '',
    impact05Title: '',
    impact05TitleArabic: '',
    impact06: '',
    impact06Title: '',
    impact06TitleArabic: '',
    latitude: '',
    longitude: '',
    colour: '',
    pushToGr: '',
    newsOnOff: false,
    tags: [],
    metaDescription: '',
    metaDescriptionArabic: ''
  },
  {
    id: '3m4l5k6j-hi89-1j01-fg67-89hi01j23m46',
    slug: 'community-jameel-saudi-arabia',
    name: 'Community Jameel Saudi Arabia',
    nameArabic: 'مجتمع جميل السعودية',
    shortname: 'CJ Saudi',
    shortNameArabic: 'مجتمع جميل السعودية',
    type: 'Programme',
    byline: 'Advancing arts, education, and social impact in Saudi Arabia',
    bylineArabic:
      'النهوض بالفنون والتعليم والأثر الاجتماعي في المملكة العربية السعودية',
    text: '<p>Community Jameel Saudi Arabia works to advance arts, education, and social impact initiatives across the Kingdom of Saudi Arabia.</p>',
    summaryLongEnglish:
      "<p>Community Jameel Saudi Arabia is dedicated to advancing arts, education, and social impact initiatives across the Kingdom of Saudi Arabia. The organization works in partnership with local institutions and communities to develop programs that support cultural preservation, educational advancement, and economic development in line with Saudi Arabia's Vision 2030.</p>",
    summaryLongArabic:
      '<p>مجتمع جميل السعودية مخصص للنهوض بمبادرات الفنون والتعليم والأثر الاجتماعي في جميع أنحاء المملكة العربية السعودية. تعمل المنظمة بالشراكة مع المؤسسات والمجتمعات المحلية لتطوير برامج تدعم الحفاظ على الثقافة والنهوض بالتعليم والتنمية الاقتصادية بما يتماشى مع رؤية السعودية 2030.</p>',
    fieldEnglishResearch: 'Arts, education, social development',
    fieldArabicResearch: 'الفنون، التعليم، التنمية الاجتماعية',
    headquartersEnglish: 'Riyadh, Saudi Arabia',
    headquartersArabic: 'الرياض، المملكة العربية السعودية',
    yearEstablished: 2020,
    yearClosed: '',
    order: '',
    status: 'published',
    createdOn: '1 January 2021',
    website: '',
    linkToPage: '',
    buttonText: '',
    twitter: '',
    facebook: '',
    instagram: '',
    linkedin: '',
    youtube: '',
    mainVideo: '',
    card: { url: '', alt: '' },
    hero: { url: '', alt: '' },
    openGraph: { url: '', alt: '' },
    logoSvgDark: { url: '', alt: '' },
    logoSvgOriginalRatio: { url: '', alt: '' },
    logoSvgSquareOverlay: { url: '', alt: '' },
    logoSvgLightOriginalRatio: { url: '', alt: '' },
    partners: [],
    leadership: [],
    relatedProgrammes: [],
    features: [],
    impact01: '',
    impact01Title: '',
    impact01TitleArabic: '',
    impact02: '',
    impact02Title: '',
    impact02TitleArabic: '',
    impact03: '',
    impact03Title: '',
    impact03TitleArabic: '',
    impact04: '',
    impact04Title: '',
    impact04TitleArabic: '',
    impact05: '',
    impact05Title: '',
    impact05TitleArabic: '',
    impact06: '',
    impact06Title: '',
    impact06TitleArabic: '',
    latitude: '',
    longitude: '',
    colour: '',
    pushToGr: '',
    newsOnOff: false,
    tags: [],
    metaDescription: '',
    metaDescriptionArabic: ''
  },
  {
    id: '4n5m6l7k-ij90-2k12-gh78-90ij12k34n57',
    slug: 'egypt-climate-lab',
    name: 'Egypt Climate Lab',
    nameArabic: 'مختبر المناخ المصري',
    shortname: 'Egypt Climate Lab',
    shortNameArabic: 'مختبر المناخ المصري',
    type: 'Lab',
    byline: 'Evidence-based climate policy solutions for Egypt',
    bylineArabic: 'حلول سياسية مناخية قائمة على الأدلة لمصر',
    text: '<p>The Egypt Climate Lab works with government partners to develop and implement evidence-based climate policy solutions.</p>',
    summaryLongEnglish:
      "<p>The Egypt Climate Lab is an embedded research initiative that works directly with Egyptian government partners to develop, test, and scale evidence-based climate policy solutions. The lab focuses on areas such as renewable energy adoption, energy efficiency, and climate adaptation strategies tailored to Egypt's specific needs and challenges.</p>",
    summaryLongArabic:
      '<p>مختبر المناخ المصري هو مبادرة بحثية مدمجة تعمل مباشرة مع الشركاء الحكوميين المصريين لتطوير واختبار وتوسيع حلول السياسة المناخية القائمة على الأدلة. يركز المختبر على مجالات مثل اعتماد الطاقة المتجددة وكفاءة الطاقة واستراتيجيات التكيف مع المناخ المصممة خصيصاً لاحتياجات وتحديات مصر.</p>',
    fieldEnglishResearch: 'Climate policy, renewable energy, adaptation',
    fieldArabicResearch: 'سياسة المناخ، الطاقة المتجددة، التكيف',
    headquartersEnglish: 'Cairo, Egypt',
    headquartersArabic: 'القاهرة، مصر',
    yearEstablished: 2023,
    yearClosed: '',
    order: '',
    status: 'published',
    createdOn: '1 January 2024',
    website: '',
    linkToPage: '',
    buttonText: '',
    twitter: '',
    facebook: '',
    instagram: '',
    linkedin: '',
    youtube: '',
    mainVideo: '',
    card: { url: '', alt: '' },
    hero: { url: '', alt: '' },
    openGraph: { url: '', alt: '' },
    logoSvgDark: { url: '', alt: '' },
    logoSvgOriginalRatio: { url: '', alt: '' },
    logoSvgSquareOverlay: { url: '', alt: '' },
    logoSvgLightOriginalRatio: { url: '', alt: '' },
    partners: [
      {
        name: 'Egyptian Government',
        slug: 'egyptian-government',
        arabicName: 'الحكومة المصرية'
      }
    ],
    leadership: [],
    relatedProgrammes: [
      {
        name: 'J-PAL Air and Water Labs',
        slug: 'jpal-air-and-water-labs',
        arabicName: 'معامل J-PAL للهواء والماء'
      }
    ],
    features: [],
    impact01: '',
    impact01Title: '',
    impact01TitleArabic: '',
    impact02: '',
    impact02Title: '',
    impact02TitleArabic: '',
    impact03: '',
    impact03Title: '',
    impact03TitleArabic: '',
    impact04: '',
    impact04Title: '',
    impact04TitleArabic: '',
    impact05: '',
    impact05Title: '',
    impact05TitleArabic: '',
    impact06: '',
    impact06Title: '',
    impact06TitleArabic: '',
    latitude: '',
    longitude: '',
    colour: '',
    pushToGr: '',
    newsOnOff: false,
    tags: [],
    metaDescription: '',
    metaDescriptionArabic: ''
  }
];

export default programmeData;
